"""User-interface copy only. Never use this module to alter meeting prompts."""

from __future__ import annotations

import re


ENGLISH: dict[str, str] = {
    "状态": "Status",
    "信息": "Info",
    "暂停": "Paused",
    "警告": "Warning",
    "总览": "Overview",
    "代裁": "Chair ruling",
    "批次": "Batch",
    "调用": "Call",
    "完成": "Done",
    "用量": "Usage",
    "任务": "Task",
    "错误": "Error",
    "开始使用": "Get started",
    "召开新会议": "Start a new meeting",
    "接续已有会议：继续流程、向主席提问，或召开后续新会": "Open a meeting: resume, ask the Chair, or start a successor",
    "管理已有会议：精简归档或彻底删除": "Manage meetings: archive or delete",
    "设置：界面外观与模型供应商": "Settings: language, appearance, and providers",
    "退出 ENSEMBLE": "Exit ENSEMBLE",
    "设置": "Settings",
    "配置摘要": "Configuration summary",
    "界面语言：中文或 English；不改变会议正文语言": "Interface language: Chinese or English; does not change report language",
    "界面外观": "Appearance",
    "颜色": "Colors",
    "表格宽度": "Table width",
    "模型供应商": "Model providers",
    "联网搜索后端：OpenAlex / Tavily": "Web search backends: OpenAlex / Tavily",
    "证据包有效期": "Evidence freshness",
    "证据包缓存最大复用时长": "Maximum evidence-cache reuse duration",
    "短：时效事实 3 天／版本资料 14 天／稳定学术事实 90 天": "Short: volatile facts 3 days / versioned sources 14 days / stable academic facts 90 days",
    "标准：7／30／180 天（推荐）": "Standard: 7 / 30 / 180 days (recommended)",
    "长：14／60／365 天；复用更多，但过期资料风险较高": "Long: 14 / 60 / 365 days; more reuse, greater stale-source risk",
    "返回首页": "Back to home",
    "界面语言 / Interface language": "Interface language / 界面语言",
    "自动检测终端": "Auto-detect terminal",
    "始终使用颜色": "Always use colors",
    "不使用颜色": "No colors",
    "紧凑（80 列）": "Compact (80 columns)",
    "标准（100 列）": "Standard (100 columns)",
    "宽屏（120 列）": "Wide (120 columns)",
    "返回设置": "Back to settings",
    "调用方式": "Provider interface",
    "OpenAI 兼容 API（DeepSeek、GLM、Kimi 等）": "OpenAI-compatible API (DeepSeek, GLM, Kimi, etc.)",
    "Google Gemini 原生 API": "Google Gemini native API",
    "Codex CLI；使用本机 ChatGPT 登录，不输入 API 密钥": "Codex CLI; use local ChatGPT login, no API key",
    "Claude Code CLI；可选本机登录或 API 密钥": "Claude Code CLI; local login or API key",
    "密钥来源": "Credential source",
    "OpenAlex 凭据": "OpenAlex credentials",
    "Tavily 凭据": "Tavily credentials",
    "网页检索补充": "Supplementary web search",
    "匿名访问（可能受到较低的服务限额约束）": "Anonymous access (possibly lower service limits)",
    "引用已有环境变量": "Use an existing environment variable",
    "引用已有外部密钥文件": "Use an existing external key file",
    "输入并保存到本机用户目录": "Enter and save in the local user directory",
    "Claude Code 凭据": "Claude Code credentials",
    "使用现有 claude auth login 登录": "Use existing claude auth login",
    "使用 API 密钥": "Use an API key",
    "引用现有全局环境变量；不保存密钥": "Use existing environment variable; do not save a key",
    "引用已有的外部密钥文件；不复制密钥": "Use existing external key file; do not copy the key",
    "现在输入密钥，保存至本机用户配置目录": "Enter a key now; save in the local user configuration directory",
    "选择摘要层级（可同时选择；回车表示都不启用）": "Choose abstract levels (both allowed; Enter skips)",
    "报告唯一输出语言": "Report output language (separate from interface language)",
    "全文摘要": "Full-report abstract",
    "逐章节摘要": "Per-section abstract",
    "分段积极性": "Paragraph-break preference",
    "行文活泼性": "Prose liveliness",
    "重绘范围": "Rendering scope",
    "Technician · 会议自修复（可选）": "Technician · meeting self-repair (optional)",
    "关闭；技术故障沿用暂停与人工处理": "Off; technical failures pause for human handling",
    "启用；故障片段可能发送给所选模型供应商；建议选最擅长 coding 的模型": "On; necessary failure excerpts may be sent to the chosen model provider; choose a strong coding model",
    "指定负责会议自修复的 Technician 模型": "Choose the Technician model for meeting repair",
    "设置 Technician 推理强度": "Set Technician reasoning effort",
    "设置核校组 reasoning effort": "Set reviewer reasoning effort",
    "指定 Chair／主渲染模型": "Choose the Chair / lead rendering model",
    "设置 Chair reasoning effort": "Set Chair reasoning effort",
    "指定 Research Desk 二次核验模型": "Choose the Research Desk recheck model",
    "设置 Research Desk reasoning effort": "Set Research Desk reasoning effort",
    "选择唯一输出语言": "Choose the report output language",
    "是否采用严格学术文章骨架": "Use a strict academic-article structure?",
    "启用": "Enable",
    "关闭": "Disable",
    "选择摘要层级": "Choose abstract levels",
    "分段积极性（1 最保守，5 最积极）": "Paragraph-break preference (1 conservative, 5 active)",
    "行文活泼性（1 最克制，5 最活泼）": "Prose liveliness (1 restrained, 5 lively)",
    "选择输出格式（至少一个）": "Choose at least one output format",
    "科学事实异议的默认裁决方式": "Default ruling on science objections",
    "由人类逐条裁决（默认）": "Human decides each item (default)",
    "授权主席逐条裁决；可在会议中随时撤销": "Authorize Chair to decide each item; revocable during the meeting",
    "科学事实组顺序（两轮均沿用）": "Science-review order (same in both rounds)",
    "选择科学复核模型（至少两个不同基础模型）": "Choose at least two different science-review models",
    "智库长推理强度": "Science-reviewer reasoning effort",
    "科学复核组（智库长）推理强度": "Science-reviewer reasoning effort",
    "指定贯穿全文的学术主笔": "Choose one writer for the entire report",
    "学术主笔推理强度": "Academic writer reasoning effort",
    "Research Desk 推理强度": "Research Desk reasoning effort",
    "是否启用 Research Desk 联网命题核实与证据收集": "Enable Research Desk for web evidence and claim checking?",
    "关闭；会议行为与旧版本一致": "Off; use the original meeting behavior",
    "启用共享、无表决权、可审计的外部证据服务": "On; shared, auditable external evidence without a vote",
    "Research Desk 运行参数": "Research Desk settings",
    "OpenAlex 每类检索返回的文献候选数": "OpenAlex candidates per search type",
    "Research Desk 独立任务最大并行度": "Research Desk maximum parallel independent tasks",
    "决策严谨度 · 重要决策需要多少赞成票": "Decision rigor · votes required for major decisions",
    "严格：部分重要决策须获全体合格投票者至少四分之三赞成；其他规则不变": "Strict: some major decisions need at least three quarters of all eligible voters; other rules unchanged",
    "宽松：这些重要决策只须获全体合格投票者过半赞成；其他规则不变": "Relaxed: those decisions need more than half of all eligible voters; other rules unchanged",
    "是否对独立的代表提交启用最大并行": "Enable maximum parallelism for independent representative submissions?",
    "关闭；使用当前模型配置或保守并发上限": "Off; use configured or conservative concurrency limits",
    "开启；每个代表模型最多同时调用 4 次，速度更快但缓存未命中可能增加": "On; up to four concurrent calls per model, faster but with more cache misses",
    "如何确定本次要核实的命题": "How to define the claim to verify",
    "直接输入已想好的最终命题": "Enter a final claim directly",
    "与筹备主席对话，逐步整理成最终命题": "Discuss with the preparatory Chair to refine the claim",
    "如何确定文献调研会议的研究任务": "How to define the literature-review task",
    "直接输入已经拟好的任务描述": "Enter a prepared task description",
    "与本次会议主席讨论，逐步形成完整研究任务": "Discuss with the Chair to develop the full research task",
    "如何确定本次议事会议的任务委托": "How to define the deliberation brief",
    "直接输入已拟好的完整任务委托": "Enter a complete prepared brief",
    "与本次会议主席对话，逐步形成完整委托": "Discuss with the Chair to develop the complete brief",
    "会前议题设计 · 与本次会议主席对话": "Pre-meeting issue design · discuss with this meeting's Chair",
    "完整候选议事委托 · 尚未启动会议": "Complete draft deliberation brief · meeting not started",
    "议事文书成文语言（与界面语言独立）": "Deliberation document language (independent of interface language)",
    "按本次任务委托指定的语言写作（默认）": "Use the language specified by this meeting's brief (default)",
    "会前任务设计 · 与本次会议主席对话": "Pre-meeting task design · discuss with this meeting's Chair",
    "完整候选研究任务 · 尚未启动会议": "Complete draft research brief · meeting not started",
    "如何处理主席提出的完整版本": "What to do with the Chair's complete draft",
    "确认采用并继续初始化": "Accept and continue setup",
    "继续讨论或提出修改意见；主席须重写整份任务": "Continue discussion or request changes; Chair rewrites the entire brief",
    "放弃对话，改为直接输入任务": "Leave dialogue and enter the task directly",
    "你": "You",
    "  这一步只设计议事委托，不开始提案、审议或表决。": "  This step designs the brief only; it does not start proposals, review, or voting.",
    "  这一步只设计研究任务，不开始文献检索或撰写报告。": "  This step designs the task only; it does not start literature search or report writing.",
    "  每次可只说一部分想法；/draft 可随时生成当前最佳版本，/back 改为直接输入。": "  Share ideas gradually; /draft shows the best current brief, and /back switches to direct entry.",
    "  发送后会完整回显你的发言，方便核对长段或多行粘贴。": "  Your complete message is echoed after sending, so you can check long or multi-line input.",
    "可选：提供人类参考资料": "Optional: add human-provided reference files",
    "文献报告的读者写作设置": "Reader-facing writing settings for the literature review",
    "不启用 Tavily；仅用 OpenAlex": "Do not use Tavily; OpenAlex only",
    "启用 Tavily；同时使用 OpenAlex 与 Tavily": "Use both Tavily and OpenAlex",
    "级别 1": "Level 1", "级别 2": "Level 2", "级别 3": "Level 3",
    "级别 4": "Level 4", "级别 5": "Level 5",
    "选择会议类型": "Choose a meeting type",
    "议事会议：模型 × 四种职位": "Deliberation: several models in four representative roles",
    "议事会议：为规则、标准或提示词委托逐条提案与表决，形成规范性文书": "Deliberation: vote on clauses for rules, criteria, or prompt briefs; produce a normative document",
    "文献调研：从新任务出发，研究并撰写完整综述报告": "Literature review: research a new task and write a full review",
    "文献调研：从新任务出发，选择简易或完整流程撰写综述报告": "Literature review: choose a simple or full workflow for a new review",
    "选择文献调研流程": "Choose a literature-review workflow",
    "简易流程：单一主笔、Research Desk 与多模型科学复核": "Simple workflow: one writer, Research Desk, and multi-model science review",
    "完整流程：多代表规划、检索、审议、写作与核校": "Full workflow: multi-representative planning, retrieval, deliberation, writing, and checks",
    "简易文献调研 · 科学复核组": "Simple literature review · science-review group",
    "  智库长是科学知识核实与检验模型：检查主笔稿中的科学判断和证据边界，不负责主笔写作或代替人类裁定。": "  Science reviewers check the writer's scientific claims and evidence boundaries; they do not write the draft or replace Human decisions.",
    "  至少选择两个不同的基础模型，以便独立指出问题；下文简称“智库长”。": "  Choose at least two distinct base models for independent review; later menus call these reviewers 'science reviewers'.",
    "  简易流程的正式会议不任命主席。你可以直接提交完整研究委托，也可以先与会前筹备主席讨论；之后学术主笔会拟定模块任务书供你批准。": "  The formal simple workflow has no Chair. Enter a complete brief or discuss it with a preparatory Chair first; the writer will then draft a module taskbook for your approval.",
    "如何确定简易文献调研的开题委托": "How to define the simple literature-review brief",
    "直接输入已拟好的完整研究委托": "Enter a complete prepared research brief",
    "与筹备主席对话，逐步形成完整研究委托": "Discuss with a preparatory Chair to develop the complete brief",
    "选择会前筹备主席模型（不加入正式简易会议）": "Choose a preparatory Chair model (not a formal meeting role)",
    "使用已选的学术主笔模型": "Use the selected academic writer model",
    "从可用模型中另选一个": "Choose another available model",
    "指定会前筹备主席模型": "Choose the preparatory Chair model",
    "设置会前筹备主席的推理强度": "Set preparatory Chair reasoning effort",
    "会前任务设计 · 与筹备主席对话": "Pre-meeting task design · discuss with a preparatory Chair",
    "  筹备主席只协助拟定开题委托；正式简易会议不任命主席。": "  The preparatory Chair helps draft the brief only; the formal simple meeting has no Chair.",
    "接续文献调研：继承既有会议资料，撰写完整综述报告": "Successor literature review: inherit prior materials and write a full report",
    "学术化重绘：继承已完成的报告，由 Chair 重绘并经科学/引文核校": "Scholarly rendering: rewrite a completed report, then check science and citations",
    "命题核实：由 Research Desk 查证一项可检验的主张": "Claim verification: Research Desk checks one testable claim",
    "快速文献调研：单一学术主笔、Research Desk 与多模型智库长科学复核": "Fast literature review: one writer, Research Desk, and multi-model science review",
    "选择模型供应商": "Choose model providers",
    "选择本次会议的基础模型": "Choose base models for this meeting",
    "设置全体代表的 reasoning effort": "Set representative reasoning effort",
    "指定 Chair 模型": "Choose the Chair model",
    "设置 Chair 的 reasoning effort": "Set Chair reasoning effort",
    "指定 Research Desk 模型": "Choose the Research Desk model",
    "设置 Research Desk 的 reasoning effort": "Set Research Desk reasoning effort",
    "指定贯穿全文的学术主笔模型": "Choose one academic writer for the full report",
    "设置学术主笔 reasoning effort": "Set academic writer reasoning effort",
    "选择科学复核模型（至少两个不同基础模型）": "Choose at least two distinct science-review models",
    "选择科学事实核校模型（至少 2 个）": "Choose at least two science-checking models",
    "选择引文核校模型（至少 2 个）": "Choose at least two citation-checking models",
    "选择一个或多个编号（逗号分隔）": "Choose one or more numbers (comma-separated)",
    "，直接回车选择全部": "; press Enter for all",
    "，直接回车跳过": "; press Enter to skip",
    "，直接回车使用默认值": "; press Enter for default",
    "选择编号: ": "Choose a number: ",
    "请输入列表中的一个编号": "Enter one listed number",
    "（或输入 b 返回）": " (or b to go back)",
    "请输入不重复的有效编号，例如 1,3。": "Enter distinct valid numbers, for example 1,3.",
    "中文": "Chinese / 中文",
    "已完成": "Completed",
    "进行中": "In progress",
    "未完成": "Unfinished",
    "已归档": "Archived",
    "手动输入源会议 ID、标题或目录": "Enter a source meeting ID, title, or path manually",
    "选择需要接续的源会议": "Choose a source meeting",
    "选择会议": "Choose a meeting",
    "是否以该会议为来源召开新会": "Start a successor meeting from this meeting?",
    "依据规范性会议的最终文书和证据包，召开文献调研报告新会": "Start a literature review using the normative meeting's final document and evidence",
    "新开学术化重绘：可选全文、局部或再次重绘；继承原稿与证据包": "Start scholarly rendering of all or part of the report; inherit source and evidence",
    "接续召开其他新会；选择需要继承的材料": "Start another successor meeting; choose inherited materials",
    "仅查看当前会议成果目录": "View this meeting's results only",
    "选择新会议继承的材料": "Choose materials for the successor meeting",
    "只继承 Research Desk 证据包与文献包": "Inherit Research Desk evidence and literature packets only",
    "只继承最终决议/报告，作为建议性前置文书": "Inherit final decision/report as advisory context only",
    "同时继承证据包与建议性最终文书": "Inherit both evidence and advisory final document",
    "继续原会议流程（沿用已落盘进度）": "Resume this meeting from saved progress",
    "与主席对话：检索当前最新草稿、证据包和文献": "Ask the Chair about the latest draft, evidence, and literature",
    "与主席对话并勘误：另存完整新版，保留原稿，不重开审核": "Discuss corrections with the Chair; save a new version without overwriting the original",
    "以当前会议为来源召开新会议": "Start a successor meeting from this one",
    "查看已完成会议的成果文件": "View completed meeting results",
    "主席问答模型": "Chair Q&A model",
    "选择本次主席问答使用的模型": "Choose the model for this Chair Q&A session",
    "设置主席问答的推理强度": "Set reasoning effort for Chair Q&A",
    "会后勘误主席": "Post-meeting correction Chair",
    "选择本次勘误主席模型": "Choose the Chair model for this correction session",
    "设置勘误主席的推理强度": "Set reasoning effort for the correction Chair",
    "返回上一级菜单": "Back to previous menu",
    "重绘全文": "Render the full report",
    "局部重绘（也可再次重绘已有重绘稿）": "Render selected sections (including already rendered sections)",
    "沿用供应商与模型默认值，不发送控制字段": "Use model/provider default; send no control field",
    "低推理强度；通常优先降低延迟与成本": "Low reasoning effort; usually lower latency and cost",
    "中等推理强度；由供应商映射到合法值": "Medium reasoning effort; mapped to a supported provider value",
    "高推理强度；通常增加延迟与推理 token": "High reasoning effort; usually more latency and reasoning tokens",
    "输入待核实的具体命题": "Enter the specific claim to verify",
    "输入人工介入通知邮箱（可留空）": "Human-escalation email (optional)",
    "输入本次学术化重绘的任务说明": "Describe this scholarly rendering task",
    "请输入完整研究委托（正式研究开始前仍会审阅模块任务书）": "Enter the complete research brief (you will still review the module taskbook before research)",
    "输入文献调研报告的任务描述": "Describe the literature-review task",
    "输入任务描述": "Describe the task",
    "输入需要学术化重绘的已完成会议目录": "Enter the completed meeting directory to render",
    "请用自然语言说明要重绘的范围；主席分割后须经你确认": "Describe the rendering scope; you will confirm the Chair's split",
    "建议正文长度（字符数；仅供写作参考，不是硬性限制，最终长度不保证；不含参考文献和独立附录）": "Suggested body length (characters; advisory only, not enforced or guaranteed; excluding references and appendices)",
    "建议正文长度（非空白字符数；仅供写作参考，不是硬性限制，最终长度不保证；不含参考文献和独立附录）": "Suggested body length (non-whitespace characters; advisory only, not enforced or guaranteed; excluding references and appendices)",
    "按顺序输入全部编号（逗号分隔）": "Enter all numbers in review order (comma-separated)",
    "每类查询最多返回多少条 [12]": "Maximum results per query type [12]",
    "输入源会议 ID、标题或目录": "Enter a source meeting ID, title, or path",
    "正在从所选供应商实时发现模型……": "Discovering models from the selected providers...",
    "供应商实时返回": "Returned by provider discovery",
    "创建会议工作区？[y/N]": "Create the meeting workspace? [y/N]",
    "快速会议至少需要两个不同模型组成智库长复核组。": "The simple workflow needs at least two distinct science-review models.",
    "请输入 1–50 的整数，或直接回车采用 12。": "Enter an integer from 1 to 50, or press Enter for 12.",
    "请输入正整数，或直接回车采用默认值。": "Enter a positive integer, or press Enter for the default.",
    "标题过长，请缩短到 72 字符以内。": "Title is too long; use no more than 72 characters.",
    "必须把每个科学核校模型恰好排列一次。": "List each science-review model exactly once.",
    "科学事实组至少需要 2 个模型。": "The science-review group needs at least two models.",
    "引文组至少需要 2 个模型。": "The citation-review group needs at least two models.",
    "源会议必须包含已完成的文献综述或学术重绘 Markdown。": "The source meeting must contain a completed literature review or scholarly-rendering Markdown file.",
    "OpenAlex 联系邮箱（可留空）": "OpenAlex contact email (optional)",
    "OpenAlex 环境变量名 [OPENALEX_API_KEY]": "OpenAlex environment variable [OPENALEX_API_KEY]",
    "OpenAlex 外部密钥文件路径": "OpenAlex external key-file path",
    "OpenAlex API 密钥（不回显）": "OpenAlex API key (hidden input)",
    "Tavily 环境变量名 [TAVILY_API_KEY]": "Tavily environment variable [TAVILY_API_KEY]",
    "Tavily 外部密钥文件路径": "Tavily external key-file path",
    "Tavily API 密钥（不回显）": "Tavily API key (hidden input)",
    "供应商显示名称（可用中文）": "Provider display name (any language)",
    "供应商代号（小写英文，会议记录将使用它，如 my_glm）": "Provider ID (lowercase ASCII, used in meeting records; e.g. my_glm)",
    "Claude CLI 命令 [claude]": "Claude CLI command [claude]",
    "Codex CLI 命令 [codex]": "Codex CLI command [codex]",
    "密钥文件路径（包含 NAME=value；不会执行文件）": "Key-file path (contains NAME=value; file is not executed)",
    "API 密钥（输入不回显）": "API key (hidden input)",
    "可用模型 ID（逗号分隔，须来自你的 Claude Code 账户）": "Available model IDs (comma-separated, from your Claude Code account)",
    "任务描述不能为空。": "Task description cannot be empty.",
    "请输入至少 1000 的正整数。": "Enter an integer of at least 1000.",
    "局部重绘不设置整篇长度目标；未选中原文必须保持不变。": "Partial rendering has no full-report length target; unselected source text must remain unchanged.",
    "  每条事实主张会分别检索支持、反证、适用范围和替代解释。": "  Each claim is searched for support, counterevidence, scope, and alternative explanations.",
    "  建议值 12；允许 1–50。直接回车采用建议值。": "  Recommended: 12; allowed range: 1–50. Press Enter for the recommendation.",
    "  仅用于独立 claim group 与现有证据覆盖检查；顺序追问仍然串行。": "  Applies only to independent claim groups and evidence-coverage checks; follow-ups remain sequential.",
    "  并行度过高可能触发限流，也可能降低 prompt cache 命中率。": "  High parallelism may trigger rate limits and reduce prompt-cache hits.",
    "  已跳过：Research Desk 联网证据服务未启用。": "  Skipped: Research Desk web evidence is disabled.",
    "  每行输入一份本地文件路径；直接回车结束。资料会复制进会议，供 Research Desk 核验。": "  Enter one local file path per line; press Enter to finish. Files are copied into the meeting for Research Desk verification.",
    "  支持 PDF、TXT、Markdown、HTML、CSV；上传后可供本会参与者查阅，请勿加入不宜公开的文件。": "  Supports PDF, TXT, Markdown, HTML, and CSV. Meeting participants may read uploads; do not add sensitive files.",
    "  上传不等于事实已获证实；扫描版 PDF 如无法提取文字，只保存原件。": "  Uploading does not verify a claim; a scanned PDF may be preserved without extractable text.",
    "先按当前文本表决第一项": "Vote on the first item using the current text",
    "暂缓当前修正案，待文本更新后重新改写": "Defer this amendment and redraft after the text changes",
    "要求主席重新审查两项修正案的关系": "Ask the Chair to re-examine the relationship between the amendments",
    "批准模块划分，开始正式文献研究": "Approve the module plan and begin formal research",
    "不批准，说明异议并彻底重做模块划分": "Reject with reasons and redo the module plan",
    "只修改文章骨架；保留已审阅的研究模块": "Revise only the article structure; keep the reviewed modules",
    "采用冻结原文": "Use the frozen source text",
    "采用当前重绘稿": "Use the current rendering draft",
    "由 Human 提供最终表述": "Human supplies the final wording",
    "采纳这条科学事实异议，交主席修稿": "Accept this scientific objection and ask the Chair to revise",
    "不采纳这条异议，交主席继续处理": "Reject this objection and let the Chair continue",
    "用一句自然语言给主席具体修改方向": "Give the Chair one sentence of revision guidance",
    "沿用已经冻结的科学核验结果": "Keep the frozen scientific verification result",
    "按当前审阅内容重新核验并另存结果": "Reverify the current review content and save a separate result",
    "仅恢复对原文忠实性的最终表决资格；不得加入未经核验的新结论": "Restore only the final vote on source fidelity; add no unverified conclusions",
    "保持暂停，暂不继续": "Stay paused for now",
    "接受正文超出预设长度范围并出版": "Accept the body-length deviation and publish",
    "跳过锚点仍有歧义的引文修正案": "Skip citation amendments with unresolved anchors",
    "保留本轮引文修改前的文本": "Keep the text from before this citation revision",
    "重新请求该核校员提交完整票集": "Ask this reviewer to resubmit a complete ballot",
    "将该核校员本轮票记为缺失票并继续": "Mark this reviewer's ballot missing and continue",
    "保留当前正文并附带引文一致性警告": "Keep the current text with a citation-consistency warning",
    "批准主席划定的局部重绘范围": "Approve the Chair's partial-rendering scope",
    "退回范围划分，并说明需要增删的部分": "Return the scope plan with requested additions or removals",
    "要求主笔只修复本次指出的段落，再作一次局部核验": "Ask the writer to repair only these paragraphs, then recheck locally",
    "知悉具体科学疑点后保留当前稿，并在报告中列出限制": "Keep the draft after reviewing the concerns, and disclose limitations",
    "继续暂停，待人工复核具体科学疑点": "Stay paused for human review of the scientific concerns",
    "批准任务书与模块划分，开始检索": "Approve the task brief and module plan; begin retrieval",
    "说明异议，交同一主笔修改任务书": "Give reasons and ask the same writer to revise the task brief",
    "按已批准的范围继续，保留范围问题记录": "Continue within approved scope and retain the scope-question record",
    "要求主笔再修订一次并复核": "Ask the writer to revise once more and recheck",
    "知悉未解决的科学异议，附限制说明后继续": "Continue with a disclosed unresolved scientific objection",
    "去除未获认可的跨模块结论后出版": "Remove unapproved cross-module conclusions before publication",
    "此项由主笔采用合理默认值，并在任务书标明": "Let the writer choose a reasonable default and mark it in the brief",
    "批准本模块提出的局部研究范围变更": "Approve the proposed local change to this module's scope",
    "总则修正案顺序处理": "Sequential processing of general-principle amendments",
    "表决程序": "Ballot procedure",
    "文献报告模块划分人工审阅": "Human review of literature-report modules",
    "学术化重绘科学事实争议": "Scientific dispute in scholarly rendering",
    "学术化重绘引文核校争议": "Citation-check dispute in scholarly rendering",
    "学术化重绘最终出版检查": "Final publication check for scholarly rendering",
    "快速文献调研 · 主笔澄清研究任务": "Fast literature review · writer clarifies the research task",
    "快速文献调研 · 人类确认任务书与模块划分": "Fast literature review · Human approves brief and module plan",
    "快速文献调研 · 模块范围确认": "Fast literature review · module-scope decision",
    "快速文献调研 · 科学异议人工决定": "Fast literature review · Human decision on scientific objection",
    "硬约束": "Hard constraints",
    "偏好": "Preferences",
    "待确认": "Open questions",
    "暂作假设": "Provisional assumptions",
    "高门槛表决": "High-threshold vote",
    "保护性表决": "Protective vote",
    "当前任务": "Current task",
    "当前子任务": "Current subtask",
    "等待调用": "Waiting to be called",
    "尚未提问": "No question submitted yet",
    "正在运行": "Running",
    "已完成": "Completed",
    "失败": "Failed",
    "已恢复完整结果": "Restored saved result",
    "已恢复检索结果": "Restored search result",
    "已调用；等待响应": "Called; awaiting response",
    "连接成功；等待首个响应": "Connected; awaiting first response",
    "等待完整响应（无流式进度）": "Waiting for complete response (no incremental progress)",
    "代表 · 规划方案": "Representatives · planning proposals",
    "Research Desk · 探索检索": "Research Desk · exploratory search",
    "重绘撰写": "Rendering draft",
    "写作提纲": "Writing outline",
    "学术主笔": "Academic writer",
    "科学性审阅": "Science review",
    "引文审阅": "Citation review",
    "引文与组装": "Citations and assembly",
}


def ui_label(chinese: str, english: str, language: str) -> str:
    """Select fixed interface copy without translating meeting-authored content."""
    return english if language == "en" else chinese


def ui_text(text: str, language: str) -> str:
    if language != "en":
        return text
    leading = text[:len(text) - len(text.lstrip())]
    trailing = text[len(text.rstrip()):]
    body = text.strip()
    if body != text:
        translated = ui_text(body, language)
        if translated != body:
            return leading + translated + trailing
    if text in ENGLISH:
        return ENGLISH[text]
    provider = re.fullmatch(r"(.+) · 凭据已检测", text)
    if provider:
        return f"{provider.group(1)} · credentials detected"
    provider = re.fullmatch(r"(.+) · 缺少 (.+)（或 api_key_file）", text)
    if provider:
        return f"{provider.group(1)} · missing {provider.group(2)} (or api_key_file)"
    provider = re.fullmatch(r"(.+) · 通过本机 Codex 登录核验；不使用 OpenAI API key", text)
    if provider:
        return f"{provider.group(1)} · local Codex login; no OpenAI API key"
    provider = re.fullmatch(r"(.+) · 使用本机 Claude Code 登录；模型由用户配置", text)
    if provider:
        return f"{provider.group(1)} · local Claude Code login; models configured by user"
    model_parts = text.split("; ")
    if model_parts and all(re.fullmatch(r"(?:输入上限|输出上限) \d+ tokens|接口 .+", part) for part in model_parts):
        return "; ".join(
            part.replace("输入上限", "Input limit", 1)
                .replace("输出上限", "Output limit", 1)
                .replace("接口", "Interface", 1)
            for part in model_parts
        )
    match = re.fullmatch(r"(\d+[a-z]?/\d+ )(.+)", text)
    if match and match.group(2) in ENGLISH:
        return match.group(1) + ENGLISH[match.group(2)]
    if text.endswith(":") or text.endswith("："):
        translated = ui_text(text[:-1], language)
        if translated != text[:-1]:
            return translated + ":"
    for source, target in ENGLISH.items():
        if source in {"，直接回车选择全部", "，直接回车跳过", "，直接回车使用默认值"}:
            text = text.replace(source, target)
    if text.startswith("选择一个或多个编号（逗号分隔）"):
        text = text.replace("选择一个或多个编号（逗号分隔）", ENGLISH["选择一个或多个编号（逗号分隔）"])
    return text
